---
- name: Restart alertmanager
  listen: "restart alertmanager"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: alertmanager
    state: restarted

- name: Reload alertmanager
  listen: "reload alertmanager"
  become: true
  ansible.builtin.systemd:
    name: alertmanager
    state: reloaded
