---
- name: Restart prometheus
  listen: "restart prometheus"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: prometheus
    state: restarted

- name: Reload prometheus
  listen: "reload prometheus"
  become: true
  ansible.builtin.systemd:
    name: prometheus
    state: reloaded
