---
- name: create logdir
  become: true
  file:
    path: "{{ postgres_exporter_log_path }}"
    owner: "{{ postgres_exporter_user }}"
    group: "{{ postgres_exporter_group }}"
    state: directory
    mode: 0750

- name: upstart service
  become: true
  template:
    src: "postgres_exporter.upstart.j2"
    dest: "/etc/init/postgres_exporter.conf"
    owner: root
    group: root
    mode: "u=rw,go=r"
  notify:
    - restart postgres_exporter
