---
- name: sysvinit service
  become: true
  template:
    src: "postgres_exporter.sysvinit.j2"
    dest: "/etc/init.d/postgres_exporter"
    owner: root
    group: root
    mode: "u=rwx,go=rx"
  notify:
    - restart postgres_exporter
