---
- name: Restart blackbox exporter
  listen: "restart blackbox exporter"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: blackbox_exporter
    state: restarted

- name: Reload blackbox exporter
  listen: "reload blackbox exporter"
  become: true
  ansible.builtin.systemd:
    name: blackbox_exporter
    state: reloaded
