---
- name: Machine setup
  hosts: all
  become: true
  roles:
    - machine_setup

- name: node exporter
  hosts: all
  roles:
    - node_exporter

# - name: Caddy for Pterodactyl Panel
#   hosts: pterodactyl_panel
#   become: true
#   roles:
#     - caddy
#   vars:
#     caddy_version: 2.6.4
#     caddy_systemd_capabilities_enabled: true
#     caddy_packages:
#       - github.com/caddy-dns/cloudflare

#     caddy_config: |
#       {
#           servers {
#               metrics
#           }
#       }

#       prometheus.ops.mareshq.com {
#           reverse_proxy 172.16.1.3:9090
#       }

#       alertmanager.ops.mareshq.com {
#           reverse_proxy 172.16.1.3:9093
#       }

- name: Postgres
  hosts: postgres
  roles:
    - postgres
  vars:
    postgresql_version: 15
    postgresql_conf:
      - listen_addresses: "'172.16.1.2, localhost'"
      - port: 5432
    postgresql_pg_hba_conf:
      - host  all  all 172.16.0.0/12 scram-sha-256


# - name: posgres exporter
#   hosts: postgres
#   roles:
#     - postgres_exporter
#   vars:
#     postgres_exporter_version: 0.13.1
#     postgres_exporter_dist: "postgres_exporter_{{ postgres_exporter_version }}_linux-arm64"
#     postgres_exporter_checksum: "sha256:bb0f12221a3aacd2c45bec9a0e2d5fb368a3e3b082f38db81bccf689398c3f2e"
