---
- name: Machine setup
  hosts: all
  become: true
  roles:
    - machine_setup

- name: node exporter
  hosts: all
  roles:
    - node_exporter

- name: Prometheus
  hosts: prometheus
  become: true
  roles:
    - prometheus
    - blackbox_exporter
  vars:
    prometheus_version: 2.45.0
    prometheus_storage_retention: 45d
    prometheus_web_listen_address: 172.16.1.3:9090
    prometheus_web_external_url: "https://prometheus.ops.mareshq.com/"
    prometheus_alertmanager_config:
      - scheme: http
        path_prefix: /
        static_configs:
          - targets: ["172.16.1.3:9093"]
    prometheus_scrape_configs:
    - job_name: "node_exporter"
      metrics_path: "/metrics"
      static_configs:
        - targets:
            - 172.16.1.1:9100
            - 172.16.1.2:9100
            - 172.16.1.3:9100
            - maple.vxm.cz:9100
            - alder.vxm.cz:9100
    - job_name: "prometheus"
      metrics_path: "/metrics"
      static_configs:
        - targets:
            - 172.16.1.3:9090
    - job_name: "alertmanager"
      metrics_path: "/metrics"
      static_configs:
        - targets:
            - 172.16.1.3:9093
    - job_name: "caddy"
      metrics_path: "/metrics"
      static_configs:
        - targets:
            - localhost:2019
    - job_name: "blackbox_exporter"
      metrics_path: "/metrics"
      static_configs:
        - targets:
            - localhost:9115

- name: Alertmanager
  hosts: prometheus
  become: true
  roles:
    - alertmanager
  vars:
    alertmanager_version: latest
    alertmanager_web_listen_address: 172.16.1.3:9093
    alertmanager_web_external_url: "https://alertmanager.ops.mareshq.com/"
    alertmanager_receivers:
      - name: slack
        slack_configs:
          - send_resolved: true
            http_config:
              follow_redirects: true
              enable_http2: true
            api_url_file: /etc/alertmanager/slack_api_url
            channel: "#general-alerts"
            text: !unsafe '{{ template "slack.default.text" . }}'
            title: !unsafe '{{ template "slack.default.title" . }}'
            icon_url: "https://avatars.githubusercontent.com/u/3380462?s=200&v=4"
            actions:
            - type: button
              text: 'Silence :no_bell:'
              url: !unsafe '{{ template "__alert_silence_link" . }}'
            - type: button
              text: 'Alertmanager :alertmanager:'
              url: !unsafe '{{ .ExternalURL }}'

    alertmanager_route:
      group_by: ["alertname", "cluster", "service"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      receiver: slack
      routes:
        - match:
            severity: critical
          receiver: slack
          continue: true
        - match:
            severity: warning
          receiver: slack
          continue: true
        - match:
            severity: info
          receiver: slack
          continue: true
        - match:
            severity: debug
          receiver: slack
          continue: true
        - match:
            alertname: Watchdog
          receiver: null

- name: Grafana
  hosts: prometheus
  become: true
  roles:
    - grafana.grafana.grafana
  vars:
    # grafana_use_provisioning: false
    grafana_address: 172.16.1.3
    grafana_port: 3000
    grafana_url: "https://grafana.ops.mareshq.com/"
    grafana_server:
      enable_gzip: true
    grafana_database:
      type: sqlite3
    grafana_security:
      admin_user: admin
      admin_password: admin
    grafana_users:
      allow_sign_up: false
      # allow_org_create: true
      # auto_assign_org: true
      auto_assign_org_role: Viewer
      # login_hint: "email or username"
      default_theme: dark
    grafana_alerting:
      execute_alerts: false
    grafana_datasources:
      - name: "Prometheus"
        type: "prometheus"
        access: "proxy"
        url: "http://172.16.1.3:9090"
        isDefault: true
        manageAlerts: false
      - name: "Alertmanager"
        type: "alertmanager"
        access: "proxy"
        url: "http://172.16.1.3:9093"
        isDefault: false
        jsonData:
          implementation: prometheus
          handleGrafanaManagedAlerts: true

- name: Caddy for Prometheus, Alertmanager and Grafana
  hosts: prometheus
  become: true
  roles:
    - caddy
  vars:
    caddy_version: 2.6.4
    caddy_systemd_capabilities_enabled: true
    caddy_environment_files:
      - /etc/caddy/.secrets.env
    caddy_packages:
      - github.com/caddy-dns/cloudflare
      - github.com/greenpau/caddy-security

    caddy_config: |
      {
          servers {
              metrics
          }
      }

      prometheus.ops.mareshq.com {
          reverse_proxy 172.16.1.3:9090

          tls {
              dns cloudflare {env.CLOUDFLARE_API_TOKEN}
          }
      }

      alertmanager.ops.mareshq.com {
          reverse_proxy 172.16.1.3:9093

          tls {
              dns cloudflare {env.CLOUDFLARE_API_TOKEN}
          }
      }

      grafana.ops.mareshq.com {
          reverse_proxy 172.16.1.3:3000

          tls {
              dns cloudflare {env.CLOUDFLARE_API_TOKEN}
          }
      }

# - name: Caddy for Pterodactyl Panel
#   hosts: pterodactyl_panel
#   become: true
#   roles:
#     - caddy
#   vars:
#     caddy_version: 2.6.4
#     caddy_systemd_capabilities_enabled: true
#     caddy_packages:
#       - github.com/caddy-dns/cloudflare

#     caddy_config: |
#       {
#           servers {
#               metrics
#           }
#       }

#       prometheus.ops.mareshq.com {
#           reverse_proxy 172.16.1.3:9090
#       }

#       alertmanager.ops.mareshq.com {
#           reverse_proxy 172.16.1.3:9093
#       }

- name: Postgres
  hosts: postgres
  roles:
    - postgres
  vars:
    postgres_version: 15

# - name: posgres exporter
#   hosts: postgres
#   roles:
#     - postgres_exporter
#   vars:
#     postgres_exporter_version: 0.13.1
#     postgres_exporter_dist: "postgres_exporter_{{ postgres_exporter_version }}_linux-arm64"
#     postgres_exporter_checksum: "sha256:bb0f12221a3aacd2c45bec9a0e2d5fb368a3e3b082f38db81bccf689398c3f2e"
