name: "Terraform: MGMT"

on:
  push:

jobs:
  mgmt-gitlab:
    name: "Terraform: MGMT GitLab"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: environments/mgmt/gitlab

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

  mgmt-terraform-cloud:
    name: "Terraform: MGMT Terraform Cloud"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: environments/mgmt/terraform-cloud

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
